window.MensercaPhraseMapEs = {
  "MENSERCA | Industrial EPC & Field Services": "MENSERCA | EPC industrial y servicios de campo",
  "html": "HTML",
  "Skip to content": "Saltar al contenido",
  "Home": "Hogar",
  "About": "Acerca de",
  "Capabilities": "Capacidades",
  "Engineering": "Ingeniería",
  "Conceptual through detailed; FEED, HAZOP, BIM": "Conceptual a través de detallado; ALIMENTACIÓN, HAZOP, BIM",
  "Procurement & Logistics": "Adquisiciones y Logística",
  "Global sourcing, QA/QC, door-to-door": "Abastecimiento global, control de calidad y control de calidad, puerta a puerta",
  "Construction & Infrastructure": "Construcción e infraestructura",
  "Civil, structural, pads, earthworks": "Civil, estructural, pads, movimiento de tierras.",
  "Mechanical & Integrity": "Mecánica e integridad",
  "Fabrication, rotating equipment, pipelines": "Fabricación, equipos rotativos, tuberías.",
  "Electrical, Instrumentation & Automation": "Electricidad, Instrumentación y Automatización",
  "Substations, MCC, control systems": "Subestaciones, CCM, sistemas de control.",
  "Industrial Maintenance": "Mantenimiento Industrial",
  "Shutdowns, static & rotating assets": "Paradas, activos estáticos y rotativos",
  "Field Operations": "Operaciones de campo",
  "Multidiscipline execution, remediation": "Ejecución multidisciplinaria, remediación.",
  "Industrial Utility Systems": "Sistemas de servicios públicos industriales",
  "Piping, steam, cooling, water, gas": "Tuberías, vapor, refrigeración, agua, gas",
  "Projects": "Proyectos",
  "Safety & Sustainability": "Seguridad y sostenibilidad",
  "Contact": "Contacto",
  "Close": "Cerca",
  "1. Hero , preview construction photo (swap URL when you have final assets)": "1. Héroe, vista previa de la foto de la construcción (intercambie la URL cuando tenga los activos finales)",
  "34 Years Leading Operational Excellence in the Energy Industry": "34 años liderando la excelencia operativa en la industria energética",
  "Multidisciplinary engineering, procurement, construction, and industrial maintenance under international quality and safety standards.": "Ingeniería multidisciplinaria, procura, construcción y mantenimiento industrial bajo estándares internacionales de calidad y seguridad.",
  "Explore technical capabilities": "Explorar capacidades técnicas",
  "Committed to excellence in every project": "Comprometidos con la excelencia en cada proyecto.",
  "2. About , preview photos via CSS variables": "2. Acerca de, vista previa de fotos mediante variables CSS",
  "Who we are": "Quienes somos",
  "About MENSERCA": "Acerca de MENSERCA",
  "Founded 1992": "Fundada en 1992",
  "34+ years": "34+ años",
  "EPC + maintenance": "EPC + mantenimiento",
  "Oil, gas & infrastructure": "Petróleo, gas e infraestructura",
  "Founded in 1992, Méndez Servicios, C.A. is an industrial contractor with 34+ years supporting oil & gas and infrastructure by integrating personnel, heavy equipment, logistics, and field execution.": "Fundada en 1992, Méndez Servicios, C.A. es un contratista industrial con más de 34 años apoyando el petróleo y el gas y la infraestructura mediante la integración de personal, equipo pesado, logística y ejecución de campo.",
  "We deliver engineering, procurement, construction, maintenance, and on-site execution for energy and infrastructure projects. Safety, efficiency, and operational delivery guide every engagement.": "Brindamos ingeniería, adquisiciones, construcción, mantenimiento y ejecución en sitio para proyectos de energía e infraestructura. La seguridad, la eficiencia y la entrega operativa guían cada compromiso.",
  "About us": "Sobre nosotros",
  "3. KPI section": "3. Sección de KPI",
  "Scale": "Escala",
  "Operational capacity": "Capacidad operativa",
  "Figures that reflect field hours, fleet, logistics reach, and workforce depth, structured for serious industrial clients.": "Cifras que reflejan horas de campo, flota, alcance logístico y profundidad de la fuerza laboral, estructuradas para clientes industriales serios.",
  "34+": "34+",
  "Years of experience": "Años de experiencia",
  "Uninterrupted industrial contracting": "Contratación industrial ininterrumpida",
  "1.2M+": "1,2 millones+",
  "Man-hours worked": "Horas hombre trabajadas",
  "Demonstrated execution volume": "Volumen de ejecución demostrado",
  "300+": "300+",
  "Qualified employees": "Empleados calificados",
  "Technical & field workforce": "Personal técnico y de campo",
  "102": "102",
  "Heavy machines": "maquinas pesadas",
  "Earthworks & industrial support": "Movimientos de tierra y soporte industrial",
  "50": "50",
  "Light vehicles": "Vehículos ligeros",
  "National logistics footprint": "Huella logística nacional",
  "3.5M+ km": "Más de 3,5 millones de kilómetros",
  "Logistics deployment": "Despliegue logístico",
  "National coverage": "Cobertura nacional",
  "4. Capabilities preview , bento rail cards": "4. Vista previa de capacidades, tarjetas bento rail",
  "What we execute": "lo que ejecutamos",
  "EPC-aligned domains from engineering through field operations. Each with dedicated technical depth.": "Dominios alineados con EPC desde la ingeniería hasta las operaciones de campo. Cada uno con profundidad técnica dedicada.",
  "FEED, basic & detailed design": "FEED, diseño básico y detallado",
  "HAZOP / LOPA, simulation, BIM": "HAZOP/LOPA, simulación, BIM",
  "ASME, API, ISO design basis": "Bases de diseño ASME, API, ISO",
  "Explore": "Explorar",
  "Global sourcing & multimodal logistics": "Abastecimiento global y logística multimodal",
  "QA/QC, nationalization support": "QA/QC, apoyo a la nacionalización",
  "Specialized technical procurement": "Contratación técnica especializada",
  "Industrial civil & structural": "Industrial civil y estructural",
  "Pads, earthworks, site development": "Plataformas, movimientos de tierra, desarrollo del sitio.",
  "Field supervision & QC": "Supervisión de campo y control de calidad",
  "Fabrication, welding, commissioning": "Fabricación, soldadura, puesta en marcha.",
  "Rotating equipment & tanks": "Equipos rotativos y tanques",
  "Integrity restoration & life extension": "Restauración de la integridad y extensión de la vida",
  "Substations & distribution": "Subestaciones y distribución",
  "Wellpad electrification, MCC": "Electrificación Wellpad, MCC",
  "Control, protection & integration": "Control, protección e integración",
  "Industrial maintenance": "mantenimiento industrial",
  "Shutdown planning & execution": "Planificación y ejecución de paradas",
  "Static & rotating equipment": "Equipos estáticos y rotativos",
  "Predictive tools & asset care": "Herramientas predictivas y cuidado de activos",
  "Including": "Incluido",
  "Field operations": "Operaciones de campo",
  "&": "&",
  "Industrial utility systems": "Sistemas de servicios industriales",
  "5. Safety preview , Petroboscán recognitions (stacked in one frame)": "5. Avance de seguridad, reconocimientos de Petroboscán (apilados en un cuadro)",
  "Commitment": "Compromiso",
  "Safety & sustainability": "Seguridad y sostenibilidad",
  "Certified management systems and disciplined HSE performance. Environmental responsibility and operational integrity are first-class.": "Sistemas de gestión certificados y desempeño disciplinado en HSE. La responsabilidad ambiental y la integridad operativa son de primera clase.",
  "ISO 9001": "Norma ISO 9001",
  "ISO 14001": "ISO 14001",
  "ISO 45001": "ISO 45001",
  "Zero fatalities; zero lost-time injuries (reporting window per company records)": "Cero muertes; cero lesiones con pérdida de tiempo (período de notificación según los registros de la empresa)",
  "Operational risk evaluation and strict PPE / lifting protocols": "Evaluación de riesgos operativos y estrictos protocolos de levantamiento/EPP",
  "Remediation, decarbonization focus, and local content commitment": "Remediación, enfoque de descarbonización y compromiso de contenido local",
  "6. Projects preview , three centered cards (photo + title + copy)": "6. Vista previa de proyectos, tres tarjetas centradas (foto + título + copia)",
  "Experience": "Experiencia",
  "Projects in execution": "Proyectos en ejecucion",
  "Active programs across major operating areas, including civil, electrical, mechanical, integrity, and environmental scopes.": "Programas activos en las principales áreas operativas, incluidos los ámbitos civil, eléctrico, mecánico, de integridad y ambiental.",
  "Petro Independencia": "petro independencia",
  "Wellpad / Pad 5, civil & electrical infrastructure, production machinery support, and well optimization services.": "Wellpad / Pad 5, infraestructura civil y eléctrica, soporte de maquinaria de producción y servicios de optimización de pozos.",
  "Petro Boscán": "Petro Boscán",
  "Large-scale corroded line replacement, preventive maintenance, asset management, storage optimization, decarbonization.": "Reemplazo de líneas corroídas a gran escala, mantenimiento preventivo, gestión de activos, optimización del almacenamiento, descarbonización.",
  "TBG": "TBG",
  "Environmental remediation, coastal recovery, critical-zone intervention, compliance, and community commitment.": "Remediación ambiental, recuperación costera, intervención en zonas críticas, cumplimiento y compromiso comunitario.",
  "Full projects portfolio": "Portafolio completo de proyectos",
  "7. Closing CTA , immersive band": "7. CTA de cierre, banda inmersiva",
  "Technical support, engineering, or field execution?": "¿Soporte técnico, ingeniería o ejecución en campo?",
  "Contact MENSERCA for technical inquiries, procurement support, and industrial projects.": "Comuníquese con MENSERCA para consultas técnicas, soporte en adquisiciones y proyectos industriales.",
  "Technical capabilities": "Capacidades técnicas",
  "MENSERCA": "MENSERCA",
  "Industrial contractor providing engineering, procurement, construction, and maintenance services.": "Contratista industrial que brinda servicios de ingeniería, adquisiciones, construcción y mantenimiento.",
  "Navigate": "Navegar por",
  "Construction & Infrastructure | MENSERCA": "Construcción e Infraestructura | MENSERCA",
  "Industrial civil and structural execution, from pads and earthworks through facilities, drainage, and field quality control.": "Ejecución civil y estructural industrial, desde plataformas y movimiento de tierras hasta instalaciones, drenaje y control de calidad en campo.",
  "Discuss scope": "Discutir el alcance",
  "Execution focus": "Enfoque de ejecución",
  "Core service areas": "Áreas de servicio principales",
  "Civil & structural": "Civiles y estructurales",
  "Industrial civil and structural works": "Obras civiles y estructurales industriales.",
  "Facility construction": "Construcción de instalaciones",
  "Civil infrastructure and support works": "Infraestructura civil y obras de apoyo.",
  "Site & terrain": "Sitio y terreno",
  "Wellpad / pad construction": "Construcción de plataforma de pozo / plataforma",
  "Site development": "Desarrollo del sitio",
  "Earthmoving, terrain preparation, excavation, grading / leveling": "Movimiento de tierras, preparación del terreno, excavación, nivelación/nivelación.",
  "Field execution quality": "Calidad de ejecución en campo",
  "Field supervision and quality control": "Supervisión de campo y control de calidad.",
  "Drainage and sanitation systems": "Sistemas de drenaje y saneamiento.",
  "Large-scale infrastructure support": "Soporte de infraestructura a gran escala",
  "Detailed technical scope": "Alcance técnico detallado",
  "Industrial buildings & civil": "Naves industriales y civiles",
  "Pads & site development": "Plataformas y desarrollo del sitio",
  "Earthworks": "Movimientos de tierra",
  "Earthmoving": "movimiento de tierras",
  "Terrain preparation": "Preparación del terreno",
  "Excavation": "Excavación",
  "Grading / leveling": "Calificación / nivelación",
  "Quality in the field": "Calidad en el campo",
  "At a glance": "De un vistazo",
  "Civil": "Civil",
  "Structural": "Estructural",
  "QC": "control de calidad",
  "Pads": "Almohadillas",
  "ISO narrative:": "Narrativa ISO:",
  "Related projects": "Proyectos relacionados",
  "Build phase delivery": "Entrega de la fase de construcción",
  "Engage our construction teams for pads, infrastructure, and industrial facilities.": "Involucrar a nuestros equipos de construcción para plataformas, infraestructura e instalaciones industriales.",
  "Next: Mechanical": "Siguiente: Mecánico",
  "Engineering | MENSERCA": "Ingeniería | MENSERCA",
  "Multidisciplinary design from concept through commissioning documentation. All work is aligned to international codes and your project stage gate.": "Diseño multidisciplinario desde el concepto hasta la documentación de puesta en marcha. Todo el trabajo está alineado con los códigos internacionales y la etapa de entrada de su proyecto.",
  "Where we focus": "donde nos enfocamos",
  "Process & design deliverables": "Entregables de proceso y diseño",
  "Conceptual, basic, detailed engineering & FEED": "Ingeniería conceptual, básica, de detalle y FEED",
  "BFD, mass/energy balances, P&IDs, plot plans": "BFD, balances de masa/energía, P&ID, planos de parcela",
  "Equipment data sheets, control philosophies": "Fichas técnicas de equipos, filosofías de control.",
  "MTO/BOM, specifications, As-Built drawings": "MTO/BOM, especificaciones, planos de construcción",
  "Risk, safety & mechanical studies": "Estudios de riesgo, seguridad y mecánica.",
  "HAZOP / LOPA": "HAZOP/LOPA",
  "Corrosion analysis & remaining life": "Análisis de corrosión y vida restante.",
  "Process simulation; tank design API 650/653": "Simulación de procesos; diseño del tanque API 650/653",
  "Piping flexibility; multidisciplinary mechanical/piping/civil": "Flexibilidad de tuberías; multidisciplinario mecánico/tuberías/civil",
  "Digital systems & PM": "Sistemas digitales y PM",
  "SCADA / PLC, ESD systems": "SCADA/PLC, sistemas ESD",
  "BIM / 3D design": "Diseño BIM/3D",
  "PMBOK-based project management": "Gestión de proyectos basada en PMBOK",
  "Design under ASME, API, ISO": "Diseño bajo ASME, API, ISO",
  "Process engineering & simulation": "Ingeniería de procesos y simulación.",
  "Mass and energy balances": "Balances de masa y energía.",
  "Process simulation": "Simulación de procesos",
  "Corrosion analysis and remaining life assessment": "Análisis de corrosión y evaluación de vida restante.",
  "Drawings, data & specifications": "Dibujos, datos y especificaciones.",
  "BFD diagrams, P&IDs, plot plans": "Diagramas BFD, P&ID, planos de trazado.",
  "As-Built drawings, MTO / BOM, technical specifications": "Planos de construcción, MTO / BOM, especificaciones técnicas",
  "Electrical, control & safety instrumented systems": "Sistemas instrumentados eléctricos, de control y seguridad.",
  "SCADA / PLC": "SCADA/PLC",
  "ESD systems": "Sistemas ESD",
  "Advanced mechanical / piping": "Mecánica avanzada / tuberías",
  "Tank design API 650 / 653": "Diseño de tanque API 650 / 653",
  "Piping flexibility analysis": "Análisis de flexibilidad de tuberías.",
  "Multidiscipline & digital delivery": "Entrega multidisciplinaria y digital",
  "Multidisciplinary engineering: mechanical, piping, electrical, control, civil, structural": "Ingeniería multidisciplinar: mecánica, tuberías, eléctrica, control, civil, estructural.",
  "Risk & compliance studies": "Estudios de riesgo y cumplimiento",
  "FEED": "ALIMENTAR",
  "HAZOP": "HAZOP",
  "LOPA": "LOPA",
  "BIM": "BIM",
  "P&ID": "P&ID",
  "ASME": "ASME",
  "API": "API",
  "ISO": "ISO",
  "ISO management system narrative: Safety & Sustainability page.": "Narrativa del sistema de gestión ISO: página de seguridad y sostenibilidad.",
  "Certifications →": "Certificaciones →",
  "Engineering for your next campaign": "Ingeniería para tu próxima campaña",
  "FEED, detailed design, or studies. Route a technical inquiry to our desk.": "FEED, diseño de detalle o estudios. Envíe una consulta técnica a nuestro escritorio.",
  "Next: Procurement": "Siguiente: Adquisiciones",
  "About | MENSERCA": "Acerca de | MENSERCA",
  "FEED, HAZOP, BIM": "ALIMENTACIÓN, HAZOP, BIM",
  "Sourcing & logistics": "Abastecimiento y logística",
  "Construction": "Construcción",
  "Civil & infrastructure": "Civiles e infraestructura",
  "Fabrication & integrity": "Fabricación e integridad",
  "Electrical & Automation": "Electricidad y Automatización",
  "Power & control": "Poder y control",
  "Shutdowns & assets": "Paradas y activos",
  "Execution & remediation": "Ejecución y remediación",
  "Utility Systems": "Sistemas de servicios públicos",
  "Piping & utilities": "Tuberías y servicios públicos",
  "Safety": "Seguridad",
  "Industrial contracting with regional reach and deep technical execution.": "Contratación industrial con alcance regional y profunda ejecución técnica.",
  "Founded in 1992, MENSERCA is a leading contractor with 34 years of uninterrupted experience in engineering, maintenance, and construction services for the oil and industrial sectors.": "Fundada en 1992, MENSERCA es una contratista líder con 34 años de experiencia ininterrumpida en servicios de ingeniería, mantenimiento y construcción para el sector petrolero e industrial.",
  "We deliver comprehensive solutions supported by a highly skilled workforce, advanced technology, and top-tier proprietary equipment.": "Ofrecemos soluciones integrales respaldadas por una fuerza laboral altamente calificada, tecnología avanzada y equipos patentados de primer nivel.",
  "With strong operational foundations in Zulia and Anzoátegui, and a key presence in El Tigre, we are strategically positioned to serve critical energy and industrial projects across the region.": "Con sólidas bases operativas en Zulia y Anzoátegui, y una presencia clave en El Tigre, estamos estratégicamente posicionados para atender proyectos energéticos e industriales críticos en toda la región.",
  "Strength": "Fortaleza",
  "What we bring": "lo que traemos",
  "Technical depth across the full project lifecycle, from design standards through safe field execution.": "Profundidad técnica en todo el ciclo de vida del proyecto, desde los estándares de diseño hasta la ejecución segura en el campo.",
  "Engineering excellence": "Excelencia en ingeniería",
  "Concept through detailed design, aligned to international codes and your technical basis.": "Concepto a través de diseño detallado, alineado a códigos internacionales y su base técnica.",
  "Shutdowns, rotating and static assets, and predictive care for continuous operations.": "Paradas, activos rotativos y estáticos, y atención predictiva para operaciones continuas.",
  "Construction execution": "Ejecución de la construcción",
  "Civil, structural, and infrastructure delivery with disciplined quality and schedule control.": "Entrega civil, estructural y de infraestructura con control disciplinado de calidad y cronograma.",
  "Advanced equipment": "Equipo avanzado",
  "Heavy machinery and logistics aligned to terrain, scope, and productivity targets.": "Maquinaria pesada y logística alineada al terreno, alcance y objetivos de productividad.",
  "Presence": "Presencia",
  "Where we operate": "donde operamos",
  "Regional foundations that keep mobilization and execution responsive.": "Fundaciones regionales que mantienen la movilización y la ejecución responsivas.",
  "Zulia": "Zulia",
  "Anzoátegui": "Anzoátegui",
  "El Tigre": "El Tigre",
  "Our commitment": "Nuestro compromiso",
  "Clients rely on MENSERCA for proven reliability, depth of experience, and execution at scale, built for long-term partnerships in demanding industrial environments.": "Los clientes confían en MENSERCA por su confiabilidad comprobada, su amplia experiencia y su ejecución a escala, diseñadas para asociaciones a largo plazo en entornos industriales exigentes.",
  "Contact | MENSERCA": "Contacto | MENSERCA",
  "FEED, HAZOP": "ALIMENTACIÓN, HAZOP",
  "Procurement": "Obtención",
  "Logistics": "Logística",
  "Infrastructure": "Infraestructura",
  "Mechanical": "Mecánico",
  "Integrity": "Integridad",
  "Electrical": "Eléctrico",
  "Automation": "Automatización",
  "Maintenance": "Mantenimiento",
  "Shutdowns": "Paradas",
  "Field": "Campo",
  "Operations": "Operaciones",
  "Utilities": "Utilidades",
  "Systems": "Sistemas",
  "Technical leads for procurement support and industrial projects.": "Lideres técnicos para soporte de adquisiciones y proyectos industriales.",
  "Eudo Méndez": "Eudo Méndez",
  "Business Director": "Director de Negocios",
  "emendez@menserca.com": "emendez@menserca.com",
  "0414 3606080": "0414 3606080",
  "Armando Méndez": "Armando Méndez",
  "Project Management / General Manager": "Gestión de Proyectos / Gerente General",
  "amendez@menserca.com": "amendez@menserca.com",
  "0412 5290856": "0412 5290856",
  "Poliana Lunar": "Pauliana Luna",
  "Administrative / Contracts": "Administrativo / Contratos",
  "plunar@menserca.com": "plunar@menserca.com",
  "0412 5290859": "0412 5290859",
  "Franclin Villadiego": "Franclin Villadiego",
  "Operations Manager": "Gerente de Operaciones",
  "fvilladiego@menserca.com": "fvilladiego@menserca.com",
  "+58 412 190 6473": "+58 412 190 6473",
  "Technical inquiry": "Consulta técnica",
  "Form layout only. Wireframe fields per brief.": "Diseño de formulario únicamente. Campos de estructura alámbrica por resumen.",
  "Company": "Compañía",
  "Position / job title": "Puesto/título del trabajo",
  "Sector": "Sector",
  "PB": "PB",
  "PI": "PI",
  "Other": "Otro",
  "Service type": "Tipo de servicio",
  "Applicable standard": "Norma aplicable",
  "Technical message": "Mensaje técnico",
  "Submit (placeholder)": "Enviar (marcador de posición)",
  "MENSERCA focuses its expertise on high-level industrial and energy infrastructure.": "MENSSERCA centra su experiencia en infraestructuras industriales y energéticas de alto nivel.",
  "Safety & Sustainability | MENSERCA": "Seguridad y Sostenibilidad | MENSERCA",
  "1. Hero , matches capability / homepage immersive pattern": "1. Hero, coincide con el patrón de inmersión de capacidad/página de inicio",
  "Highest standards of safety, operational integrity, environmental responsibility, and continuous risk control across all operations.": "Los más altos estándares de seguridad, integridad operativa, responsabilidad ambiental y control continuo de riesgos en todas las operaciones.",
  "Contact HSE": "Contacto HSE",
  "Back to home": "De vuelta a casa",
  "2. HSE + certifications | client recognition (split)": "2. Certificaciones HSE+ | reconocimiento del cliente (dividido)",
  "HSE & certified management": "HSE y gestión certificada",
  "MENSERCA is committed to the highest standards of safety, operational integrity, environmental responsibility, and continuous risk control, protecting personnel, equipment, and infrastructure under ISO 9001, ISO 14001, and ISO 45001.": "MENSSERCA está comprometida con los más altos estándares de seguridad, integridad operativa, responsabilidad ambiental y control continuo de riesgos, protegiendo al personal, equipos e infraestructura bajo las normas ISO 9001, ISO 14001 e ISO 45001.",
  "ISO 9001: Quality": "ISO 9001: Calidad",
  "ISO 14001: Environment": "ISO 14001: Medio Ambiente",
  "ISO 45001: Safety": "ISO 45001: Seguridad",
  "3. Three pillars , equal-height cards, hover": "3. Tres pilares, cartas de igual altura, flotando",
  "How we work": "como trabajamos",
  "Operational focus, risk evaluation, and field measures": "Enfoque operativo, evaluación de riesgos y medidas de campo.",
  "Three pillars of HSE execution, aligned and consistent across sites.": "Tres pilares de ejecución de HSE, alineados y consistentes en todos los sitios.",
  "Operational focus": "Enfoque operativo",
  "Accident prevention": "Prevención de accidentes",
  "Personnel protection": "Protección del personal",
  "Protocol improvement": "Mejora del protocolo",
  "Risk evaluation": "Evaluación de riesgos",
  "Weight & falling-risk assessment": "Evaluación de peso y riesgo de caídas",
  "Consequence analysis": "Análisis de consecuencias",
  "High-risk zone identification": "Identificación de zonas de alto riesgo",
  "Safety measures": "Medidas de seguridad",
  "Mandatory PPE": "EPI obligatorio",
  "Continuous site control": "Control continuo del sitio",
  "Safe lifting procedures": "Procedimientos de elevación seguros",
  "4. KPI band , unified background, one grid system": "4. Banda KPI, fondo unificado, un sistema de cuadrícula",
  "Performance": "Actuación",
  "HSE performance (sample window)": "Rendimiento HSE (ventana de muestra)",
  "225,306 man-hours (2022–2024) • 0 fatalities • 0 lost-time injuries.": "225,306 horas-hombre (2022-2024) • 0 muertes • 0 lesiones con tiempo perdido.",
  "225k+": "225k+",
  "Man-hours": "Horas-hombre",
  "2022–2024": "2022-2024",
  "0": "0",
  "Fatalities": "Muertes",
  "Lost-time injuries": "Lesiones con tiempo perdido",
  "Procurement & Logistics | MENSERCA": "Adquisiciones y Logística | MENSERCA",
  "Critical equipment and materials sourced globally, validated technically, and delivered with multimodal logistics and nationalization support.": "Equipos y materiales críticos obtenidos globalmente, validados técnicamente y entregados con logística multimodal y soporte de nacionalización.",
  "Sourcing & supplier coordination": "Coordinación de abastecimiento y proveedores.",
  "Global sourcing of critical equipment and materials": "Abastecimiento global de equipos y materiales críticos",
  "Coordination of international suppliers": "Coordinación de proveedores internacionales.",
  "Alliances with authorized manufacturers": "Alianzas con fabricantes autorizados",
  "Logistics & nationalization": "Logística y nacionalización",
  "Maritime, air, and land logistics": "Logística marítima, aérea y terrestre",
  "Customs / nationalization management": "Gestión aduanera/nacionalización",
  "Door-to-door delivery": "Entrega puerta a puerta",
  "Quality & specialized procurement": "Calidad y adquisiciones especializadas",
  "QA/QC": "control de calidad/control de calidad",
  "ASTM, ANSI, ISO certification support": "Soporte de certificación ASTM, ANSI, ISO",
  "Specialized technical procurement: valves, instrumentation, specialty piping": "Contratación técnica especializada: válvulas, instrumentación, tuberías especiales.",
  "Sourcing footprint": "Huella de abastecimiento",
  "Sourcing in the U.S., Europe, and Asia": "Abastecimiento en EE. UU., Europa y Asia",
  "Logistics execution": "Ejecución logística",
  "Assurance & standards": "Garantía y estándares",
  "Specialized categories": "Categorías especializadas",
  "ASTM": "ASTM",
  "ANSI": "ANSI",
  "Customs": "Aduanas",
  "Procurement for your next package": "Adquisiciones para su próximo paquete",
  "Request technical procurement and logistics support for industrial projects.": "Solicitar soporte técnico en adquisiciones y logística para proyectos industriales.",
  "Next: Construction": "Siguiente: Construcción",
  "Projects | MENSERCA": "Proyectos | MENSERCA",
  "Featured programs": "Programas destacados",
  "Project 01": "Proyecto 01",
  "Wellpad and civil–electrical infrastructure with production support, wells analysis, and optimization of producing assets.": "Wellpad e infraestructura civil-eléctrica con soporte a la producción, análisis de pozos y optimización de activos productores.",
  "Wellpad / Pad 5 construction": "Construcción Wellpad / Pad 5",
  "Civil and electrical infrastructure": "Infraestructura civil y eléctrica",
  "Production machinery support": "Soporte de maquinaria de producción.",
  "Wells support, analysis, maintenance, and production well optimization": "Soporte de pozos, análisis, mantenimiento y optimización de pozos de producción.",
  "Project 02": "Proyecto 02",
  "Large-scale line replacement and sustaining work across flow stations, with asset management, storage optimization, and decarbonization focus.": "Reemplazo de líneas a gran escala y trabajos de mantenimiento en estaciones de flujo, con enfoque en la gestión de activos, la optimización del almacenamiento y la descarbonización.",
  "Large-scale replacement of corroded lines (up to ~20 km coverage)": "Reemplazo a gran escala de líneas corroídas (hasta ~20 km de cobertura)",
  "Minor maintenance and preventive services": "Servicios menores de mantenimiento y preventivos.",
  "Asset management and storage optimization": "Gestión de activos y optimización del almacenamiento.",
  "Decarbonization initiatives and flow stations focus": "Iniciativas de descarbonización y estaciones de flujo se centran",
  "Project 03": "Proyecto 03",
  "Environmental remediation and coastal recovery in critical operational zones, with mitigation, compliance, and community engagement.": "Remediación ambiental y recuperación costera en zonas operativas críticas, con mitigación, cumplimiento y participación comunitaria.",
  "Environmental remediation and coastal recovery": "Remediación ambiental y recuperación costera",
  "Critical operational zones and mitigation": "Zonas operativas críticas y mitigación",
  "Regulatory compliance": "Cumplimiento normativo",
  "Local content and communities": "Contenido local y comunidades",
  "Field Operations | MENSERCA": "Operaciones de campo | MENSERCA",
  "Multidiscipline field execution across civil, mechanical, and electrical scopes, with inspection, environmental sampling, and remediation.": "Ejecución de campo multidisciplinaria en ámbitos civil, mecánico y eléctrico, con inspección, muestreo ambiental y remediación.",
  "Discipline execution": "Ejecución de disciplina",
  "Field execution in civil, mechanical, and electrical operations": "Ejecución en campo en operaciones civiles, mecánicas y eléctricas.",
  "Mechanical fabrication, welding, and field pipeline installation": "Fabricación mecánica, soldadura e instalación de tuberías en campo.",
  "Electrical infrastructure, control, and instrumentation integration": "Integración de infraestructura eléctrica, control e instrumentación.",
  "Inspection & environment": "Inspección y medio ambiente",
  "Field inspection": "Inspección de campo",
  "Environmental sampling": "Muestreo ambiental",
  "Operational evaluation of coastal and industrial areas": "Evaluación operativa de zonas costeras e industriales.",
  "Site services": "Servicios del sitio",
  "Site development and material handling": "Desarrollo del sitio y manejo de materiales.",
  "Industrial cleaning": "Limpieza industrial",
  "Vegetation control": "control de vegetación",
  "Operational and environmental remediation": "Remediación operativa y ambiental",
  "Civil / mechanical / electrical": "Civil/mecánico/eléctrico",
  "Inspection & sampling": "Inspección y muestreo",
  "Site & remediation": "Sitio y remediación",
  "Remediation": "Remediación",
  "Welding": "Soldadura",
  "Pipelines": "Tuberías",
  "Field execution": "Ejecución de campo",
  "Mobilize multidiscipline crews for industrial and environmental field programs.": "Movilizar equipos multidisciplinarios para programas de campo industriales y ambientales.",
  "Next: Utility systems": "Siguiente: Sistemas de servicios públicos",
  "Mechanical & Integrity | MENSERCA": "Mecánica e integridad | MENSERCA",
  "Installation, fabrication, integrity restoration, and life extension for rotating equipment, piping, tanks, and structures.": "Instalación, fabricación, restauración de la integridad y extensión de la vida útil de equipos rotativos, tuberías, tanques y estructuras.",
  "Fabrication & erection": "Fabricación y montaje",
  "Fabrication and erection of steel structures": "Fabricación y montaje de estructuras de acero.",
  "Precision welding; API/ASME spools": "Soldadura de precisión; Carretes API/ASME",
  "Installation and maintenance of industrial equipment": "Instalación y mantenimiento de equipos industriales.",
  "Rotating equipment & commissioning": "Equipos rotativos y puesta en marcha",
  "Commissioning": "Puesta en servicio",
  "Laser alignment; equipment balancing": "Alineación láser; equilibrio de equipos",
  "Overhaul of pumps, compressors, and turbines": "Revisión de bombas, compresores y turbinas.",
  "Integrity & life extension": "Integridad y extensión de vida",
  "Tank inspection, construction, and maintenance": "Inspección, construcción y mantenimiento de tanques.",
  "Corrosion mitigation and damage control": "Mitigación de la corrosión y control de daños.",
  "Pipeline integrity restoration; remaining life assessment": "Restauración de la integridad de las tuberías; evaluación de vida restante",
  "Infrastructure life extension; preventive and corrective interventions": "Extensión de la vida de la infraestructura; intervenciones preventivas y correctivas",
  "Structures & welding": "Estructuras y soldadura",
  "Precision welding": "Soldadura de precisión",
  "API/ASME spools": "Carretes API/ASME",
  "Rotating & static equipment": "Equipos rotativos y estáticos.",
  "Alignment & commissioning": "Alineación y puesta en marcha",
  "Laser alignment": "Alineación láser",
  "Equipment balancing": "Equilibrio de equipos",
  "Integrity programs": "Programas de integridad",
  "Composite material repairs": "Reparaciones de materiales compuestos.",
  "Pipeline integrity restoration": "Restauración de la integridad de la tubería",
  "Preventive and corrective technical interventions": "Intervenciones técnicas preventivas y correctivas",
  "Remaining life assessment of critical assets": "Evaluación de vida restante de activos críticos",
  "Infrastructure life extension": "Extensión de la vida de la infraestructura",
  "NDT": "END",
  "Mechanical & integrity campaigns": "Campañas mecánicas y de integridad.",
  "Plan fabrication, overhaul, or integrity restoration with our technical teams.": "Planifique la fabricación, revisión o restauración de la integridad con nuestros equipos técnicos.",
  "Next: Electrical": "Siguiente: Eléctrico",
  "Electrical, Instrumentation & Automation | MENSERCA": "Eléctrica, Instrumentación y Automatización | MENSERCA",
  "Power systems, substations, wellpad electrification, and industrial control, from protection and grounding through integration.": "Sistemas de energía, subestaciones, electrificación de pozos y control industrial, desde protección y puesta a tierra hasta la integración.",
  "Power & distribution": "Energía y distribución",
  "VFD integration": "Integración VFD",
  "Power systems; transmission lines (13.8 kV / 34.5 kV)": "Sistemas de energía; líneas de transmisión (13,8 kV / 34,5 kV)",
  "Medium- and high-voltage substations; power transformers; generators; MCCs": "Subestaciones de media y alta tensión; transformadores de potencia; generadores; MCC",
  "Power distribution centers; grounding systems": "Centros de distribución de energía; sistemas de puesta a tierra",
  "Facilities & wellpads": "Instalaciones y pozos",
  "Wellpad electrification": "Electrificación de pozos",
  "Shelters / control rooms": "Refugios/salas de control",
  "Breakers and lightning protection; backup power systems; lighting systems": "Disyuntores y protección contra rayos; sistemas de energía de respaldo; sistemas de iluminación",
  "Instrumentation & control": "Instrumentación y control",
  "Measurement, protection, and control systems": "Sistemas de medida, protección y control.",
  "Industrial control and instrumentation": "Control e instrumentación industrial.",
  "Control and instrumentation integration": "Integración de control e instrumentación.",
  "Power infrastructure": "Infraestructura eléctrica",
  "Power systems": "Sistemas de energía",
  "Transmission lines (13.8 kV / 34.5 kV)": "Líneas de transmisión (13,8 kV / 34,5 kV)",
  "Medium- and high-voltage substations": "Subestaciones de media y alta tensión",
  "Power transformers": "Transformadores de potencia",
  "Generators": "Generadores",
  "MCCs": "MCC",
  "Power distribution centers": "Centros de distribución de energía",
  "Grounding & site power": "Conexión a tierra y alimentación del sitio",
  "Grounding systems": "Sistemas de puesta a tierra",
  "Backup power systems": "Sistemas de energía de respaldo",
  "Lighting systems": "Sistemas de iluminación",
  "Protection & facilities": "Protección e instalaciones",
  "Breakers and lightning protection": "Disyuntores y protección contra rayos.",
  "Instrumentation": "Instrumentación",
  "HV": "alto voltaje",
  "MCC": "MCC",
  "Substation": "Subestación",
  "VFD": "VFD",
  "PLC": "SOCIEDAD ANÓNIMA",
  "ESD": "ESD",
  "Power & control delivery": "Entrega de energía y control",
  "Scope substations, wellpad power, or C&I integration for your next project.": "Alcance las subestaciones, la energía de los pozos o la integración de C&I para su próximo proyecto.",
  "Next: Maintenance": "Siguiente: Mantenimiento",
  "Industrial Utility Systems | MENSERCA": "Sistemas de servicios públicos industriales | MENSERCA",
  "Process piping, flowlines, fluids transport, and utility packages for steam, cooling, air, gas, and water.": "Tuberías de proceso, líneas de flujo, transporte de fluidos y paquetes de servicios públicos para vapor, refrigeración, aire, gas y agua.",
  "Piping & transport": "Tuberías y transporte",
  "Process piping systems": "Sistemas de tuberías de proceso",
  "Flowlines and production lines": "Líneas de flujo y líneas de producción.",
  "Replacement of corroded pipelines (up to ~20 km)": "Reemplazo de tuberías corroídas (hasta ~20 km)",
  "Transport systems for water, gas, and industrial fluids": "Sistemas de transporte de agua, gas y fluidos industriales.",
  "Thermal & air": "Térmica y aire",
  "Steam generation and condensate return": "Generación de vapor y retorno de condensado.",
  "Industrial cooling systems and chillers": "Sistemas de refrigeración y enfriadoras industriales.",
  "Compressed air systems": "Sistemas de aire comprimido",
  "Gas & water": "Gas y agua",
  "LP gas and natural gas systems": "Sistemas de gas LP y gas natural",
  "Water treatment and handling systems": "Sistemas de tratamiento y manipulación de agua.",
  "Piping & lines": "Tuberías y líneas",
  "Replacement of corroded pipelines up to 20 km": "Reemplazo de tuberías corroídas hasta 20 km.",
  "Steam & cooling": "Vapor y enfriamiento",
  "Piping": "Tubería",
  "Steam": "Vapor",
  "Chiller": "enfriador",
  "Flowline": "Línea de flujo",
  "Gas": "Gas",
  "Water": "Agua",
  "Utility system delivery": "Entrega del sistema de servicios públicos",
  "Engineer and install piping and utility packages aligned to your process design.": "Diseñe e instale paquetes de tuberías y servicios públicos alineados con el diseño de su proceso.",
  "Industrial Maintenance | MENSERCA": "Mantenimiento Industrial | MENSERCA",
  "Shutdowns, operational maintenance, and asset programs for static and rotating equipment, controls, and predictive tools.": "Paradas, mantenimiento operativo y programas de activos para equipos estáticos y rotativos, controles y herramientas predictivas.",
  "Shutdowns & campaigns": "Paradas y campañas",
  "Plant shutdown planning and execution": "Planificación y ejecución de paradas de planta.",
  "Preventive and corrective maintenance": "Mantenimiento preventivo y correctivo.",
  "Operational maintenance": "Mantenimiento operativo",
  "Equipment classes": "Clases de equipos",
  "Maintenance of static equipment": "Mantenimiento de equipos estáticos.",
  "Refurbishment of rotating equipment": "Renovación de equipos rotativos.",
  "Non-destructive testing": "Pruebas no destructivas",
  "Systems & digital": "Sistemas y digitales",
  "Rehabilitation of control systems": "Rehabilitación de sistemas de control.",
  "Asset management": "Gestión de activos",
  "Predictive maintenance supported by digital tools and drones where appropriate": "Mantenimiento predictivo apoyado en herramientas digitales y drones cuando corresponda",
  "Static & rotating": "Estático y giratorio",
  "Controls": "Controles",
  "Programs": "Programas",
  "Shutdown": "Cerrar",
  "Predictive": "Profético",
  "Assets": "Activos",
  "Maintenance readiness": "Preparación para el mantenimiento",
  "Plan shutdowns, campaigns, or operational maintenance with MENSERCA.": "Planifica paradas, campañas o mantenimientos operativos con MENSERCA.",
  "Next: Field operations": "Siguiente: Operaciones de campo",
  "Capabilities | MENSERCA": "Capacidades | MENSERCA",
  "Eight integrated domains, from engineering through utility systems, and each with its own technical scope page.": "Ocho dominios integrados, desde ingeniería hasta sistemas de servicios públicos, y cada uno con su propia página de alcance técnico.",
  "EPC & execution": "EPC y ejecución",
  "Select a domain": "Seleccione un dominio",
  "Open the full service layout for procurement, construction, maintenance, field work, and utilities.": "Abra el diseño de servicio completo para adquisiciones, construcción, mantenimiento, trabajo de campo y servicios públicos.",
  "Conceptual, basic & detailed": "Conceptual, básico y detallado.",
  "FEED, HAZOP, LOPA, BIM": "ALIMENTACIÓN, HAZOP, LOPA, BIM",
  "Open": "Abierto",
  "Global sourcing": "Abastecimiento global",
  "Multimodal logistics": "Logística multimodal",
  "QA/QC & nationalization": "Control de calidad y nacionalización",
  "Pads, earthworks, drainage": "Plataformas, movimiento de tierras, drenaje.",
  "Fabrication & welding": "Fabricación y soldadura",
  "Wellpad power, MCC, protection": "Alimentación Wellpad, MCC, protección",
  "Control & integration": "Control e integración",
  "Static & rotating assets": "Activos estáticos y rotativos",
  "Predictive & asset management": "Gestión predictiva y de activos",
  "Multidiscipline field execution": "Ejecución de campo multidisciplinar",
  "Inspection & environmental sampling": "Inspección y muestreo ambiental.",
  "Remediation & site services": "Servicios de remediación y sitio",
  "Process piping & flowlines": "Tuberías y líneas de flujo de proceso",
  "Steam, cooling, air, gas, water": "Vapor, refrigeración, aire, gas, agua.",
  "Long-distance line replacement": "Reemplazo de línea de larga distancia",
  "Need a bundled EPC scope?": "¿Necesita un alcance EPC incluido?",
  "Tell us which domains apply. Our team routes technical inquiries to the right discipline leads.": "Díganos qué dominios aplican. Nuestro equipo dirige las consultas técnicas a los líderes disciplinarios adecuados."
};
