window.MensercaPhraseMapEs = {
  " and ": " y ",
  "&": "&",
  "+58 412 190 6473": "+58 412 190 6473",
  "0": "0",
  "0412 5290856": "0412 5290856",
  "0412 5290859": "0412 5290859",
  "0414 3606080": "0414 3606080",
  "1. Hero , matches capability / homepage immersive pattern": "1. Hero, coincide con el patrón de inmersión de capacidad/página de inicio",
  "1. Hero , preview construction photo (swap URL when you have final assets)": "1. Héroe, vista previa de la foto de la construcción (intercambie la URL cuando tenga los activos finales)",
  "1.2M+": "1,2 millones+",
  "102": "102",
  "2. About , preview photos via CSS variables": "2. Acerca de, vista previa de fotos mediante variables CSS",
  "2. HSE + certifications | client recognition (split)": "2. Certificaciones HSE+ | reconocimiento del cliente (dividido)",
  "2022–2024": "2022-2024",
  "225,306 man-hours (2022–2024) • 0 fatalities • 0 lost-time injuries.": "225.306 horas-hombre (2022–2024) • 0 muertes • 0 lesiones con pérdida de tiempo.",
  "225k+": "225K+",
  "3. KPI section": "3. Sección de KPI",
  "3. Three pillars , equal-height cards, hover": "3. Tres pilares, cartas de igual altura, flotando",
  "5+ km": "5+ km",
  "Process pipeline installation": "Instalación de tuberías de proceso",
  "300+": "300+",
  "34 Years Leading Operational Excellence in the Energy Industry": "34 años impulsando la excelencia operativa",
  "34 years delivering operational excellence": "34 años impulsando la excelencia operativa",
  "34+": "34+",
  "34+ years": "34+ años",
  "4. Capabilities preview , bento rail cards": "4. Vista previa de capacidades, tarjetas bento rail",
  "4. KPI band , unified background, one grid system": "4. Banda KPI, fondo unificado, un sistema de cuadrícula",
  "5. Safety preview , Petroboscán recognitions (stacked in one frame)": "5. Avance de seguridad, reconocimientos de Petroboscán (apilados en un cuadro)",
  "50": "50",
  "6. Projects preview , three centered cards (photo + title + copy)": "6. Vista previa de proyectos, tres tarjetas centradas (foto + título + copia)",
  "7. Closing CTA , immersive band": "7. CTA de cierre, banda inmersiva",
  "ANSI": "ANSI",
  "API": "API",
  "API/ASME spools": "carretes API/ASME",
  "ASME": "ASME",
  "ASME, API, ISO design basis": "Bases de diseño ASME, API, ISO",
  "ASTM": "ASTM",
  "ASTM, ANSI, ISO certification support": "Soporte de certificación ASTM, ANSI, ISO",
  "About": "Acerca de",
  "About MENSERCA": "Acerca de MENSERCA",
  "About us": "Sobre nosotros",
  "About | MENSERCA": "Acerca de | MENSERCA",
  "Accident prevention": "Prevención de accidentes",
  "Active programs across major operating areas, including civil, electrical, mechanical, integrity, and environmental scopes.": "Programas activos en las principales áreas operativas, incluidos los ámbitos civil, eléctrico, mecánico, de integridad y ambiental.",
  "Administrative / Contracts": "Administrativo / Contratos",
  "Advanced equipment": "Equipo avanzado",
  "Advanced mechanical / piping": "Mecánica avanzada / tuberías",
  "Alignment & commissioning": "Alineación y puesta en marcha",
  "Alliances with authorized manufacturers": "Alianzas con fabricantes autorizados",
  "Anzoátegui": "Anzoátegui",
  "Applicable standard": "Norma aplicable",
  "Armando Méndez": "Armando Méndez",
  "As-Built drawings, MTO / BOM, technical specifications": "Planos de construcción, MTO / BOM, especificaciones técnicas",
  "Asset management": "Gestión de activos",
  "Asset management and storage optimization": "Gestión de activos y optimización del almacenamiento.",
  "Assets": "Activos",
  "Assurance & standards": "Garantía y estándares",
  "At a glance": "De un vistazo",
  "Automation": "Automatización",
  "BFD diagrams, P&IDs, plot plans": "Diagramas BFD, P&ID, planos de trazado.",
  "BFD, mass/energy balances, P&IDs, plot plans": "BFD, balances de masa/energía, P&ID, planos de parcela",
  "BIM": "BIM",
  "BIM / 3D design": "Diseño BIM/3D",
  "Back to home": "Regresar al inicio",
  "Backup power systems": "Sistemas de energía de respaldo",
  "Breakers and lightning protection": "Disyuntores y protección contra rayos.",
  "Breakers and lightning protection; backup power systems; lighting systems": "Disyuntores y protección contra rayos; sistemas de energía de respaldo; sistemas de iluminación",
  "Build phase delivery": "Entrega de la fase de construcción",
  "Business Director": "Director de Negocios",
  "CO2 emission reduction and flow control": "Reducción de emisiones de CO₂ y control de flujo",
  "Capabilities": "Capacidades",
  "Capabilities | MENSERCA": "Capacidades | MENSERCA",
  "Certifications →": "Certificaciones →",
  "Certified management systems and disciplined HSE performance. Environmental responsibility and operational integrity are first-class.": "Sistemas de gestión certificados y desempeño disciplinado en HSE. La responsabilidad ambiental y la integridad operativa forman parte de nuestros estándares fundamentales.",
  "Chiller": "Enfriadoras",
  "Civil": "Civil",
  "Civil & infrastructure": "Civiles e infraestructura",
  "Civil & structural": "Civiles y estructurales",
  "Civil / mechanical / electrical": "Civil/mecánico/eléctrico",
  "Civil and electrical infrastructure": "Infraestructura civil y eléctrica",
  "Civil infrastructure and support works": "Infraestructura civil y obras de apoyo.",
  "Civil, structural, and infrastructure delivery with disciplined quality and schedule control.": "Entrega civil, estructural y de infraestructura con control disciplinado de calidad y cronograma.",
  "Civil, structural, pads, earthworks": "Civil, estructural, pads, movimiento de tierras.",
  "Clients rely on MENSERCA for proven reliability, depth of experience, and execution at scale, built for long-term partnerships in demanding industrial environments.": "Los clientes confían en MENSERCA por su confiabilidad comprobada, su amplia experiencia y su ejecución a escala, diseñadas para alianzas a largo plazo en entornos industriales exigentes.",
  "Close": "Cerrar",
  "Commissioning": "Puesta en servicio",
  "Commitment": "Compromiso",
  "Committed to excellence in every project": "Comprometidos con la excelencia en cada proyecto.",
  "Company": "Compañía",
  "Composite material repairs": "Reparaciones de materiales compuestos.",
  "Compressed air systems": "Sistemas de aire comprimido",
  "Concept through detailed design, aligned to international codes and your technical basis.": "Concepto a través de diseño detallado, alineado a códigos internacionales y su base técnica.",
  "Conceptual through detailed; FEED, HAZOP, BIM": "Conceptual a detallado; FEED, HAZOP, BIM",
  "Conceptual, basic & detailed": "Conceptual, básico y detallado.",
  "Conceptual, basic, detailed engineering & FEED": "Ingeniería conceptual, básica, de detalle y FEED",
  "Consequence analysis": "Análisis de consecuencias",
  "Construction": "Construcción",
  "Construction & Infrastructure": "Construcción e infraestructura",
  "Construction & Infrastructure | MENSERCA": "Construcción e infraestructura | MENSERCA",
  "Construction execution": "Ejecución de la construcción",
  "Contact": "Contacto",
  "Contact HSE": "Contacto HSE",
  "Contact MENSERCA for technical inquiries, procurement support, and industrial projects.": "Comuníquese con MENSERCA para consultas técnicas, soporte en procura y proyectos industriales.",
  "Contact | MENSERCA": "Contacto | MENSERCA",
  "Continuous site control": "Control continuo del sitio",
  "Control & integration": "Control e integración",
  "Control and instrumentation integration": "Integración de control e instrumentación.",
  "Control, protection & integration": "Control, protección e integración",
  "Controls": "Controles",
  "Coordination of international suppliers": "Coordinación de proveedores internacionales.",
  "Core service areas": "Áreas de servicio principales",
  "Corrosion analysis & remaining life": "Análisis de corrosión y vida restante.",
  "Corrosion analysis and remaining life assessment": "Análisis de corrosión y evaluación de vida restante.",
  "Corrosion mitigation and damage control": "Mitigación de la corrosión y control de daños.",
  "Critical equipment and materials sourced globally, validated technically, and delivered with multimodal logistics and nationalization support.": "Equipos y materiales críticos obtenidos globalmente, validados técnicamente y entregados con logística multimodal y soporte de nacionalización.",
  "Critical operational zones and mitigation": "Zonas operativas críticas y mitigación",
  "Customs": "Aduanas",
  "Customs / nationalization management": "Gestión aduanera y nacionalización",
  "Decarbonization initiatives and flow stations focus": "Iniciativas de descarbonización en estaciones de flujo",
  "Demonstrated execution volume": "Volumen de ejecución demostrado",
  "Design under ASME, API, ISO": "Diseño bajo ASME, API, ISO",
  "Detailed technical scope": "Alcance técnico detallado",
  "Digital systems & PM": "Sistemas digitales y PM",
  "Discipline execution": "Ejecución multidisciplinaria",
  "Discuss scope": "Consultar alcance",
  "Door-to-door delivery": "Entrega puerta a puerta",
  "Drainage and sanitation systems": "Sistemas de drenaje y saneamiento.",
  "Drawings, data & specifications": "Dibujos, datos y especificaciones.",
  "EPC & execution": "EPC y ejecución",
  "EPC + maintenance": "EPC + mantenimiento",
  "EPC-aligned domains from engineering through field operations. Each with dedicated technical depth.": "Dominios alineados con EPC desde la ingeniería hasta las operaciones en campo. Cada uno con profundidad técnica dedicada.",
  "ESD": "ESD",
  "ESD systems": "Sistemas ESD.",
  "Earthmoving": "Movimiento de tierras",
  "Earthmoving, terrain preparation, excavation, grading / leveling": "Movimiento de tierras, preparación del terreno, excavación, nivelación",
  "Earthworks": "Movimiento de tierras",
  "Earthworks & industrial support": "Movimiento de tierra y soporte industrial",
  "Eight integrated domains, from engineering through utility systems, and each with its own technical scope page.": "Ocho dominios integrados, desde ingeniería hasta sistemas de servicios industriales, y cada uno con su propia página de alcance técnico.",
  "El Tigre": "El Tigre",
  "Electrical": "Eléctrico",
  "Electrical & Automation": "Electricidad y Automatización",
  "Electrical infrastructure, control, and instrumentation integration": "Integración de infraestructura eléctrica, control e instrumentación.",
  "Electrical, Instrumentation & Automation": "Electricidad, instrumentación y automatización",
  "Electrical, Instrumentation & Automation | MENSERCA": "Electricidad, instrumentación y automatización | MENSERCA",
  "Electrical, control & safety instrumented systems": "Sistemas instrumentados eléctricos, de control y seguridad.",
  "Engage our construction teams for pads, infrastructure, and industrial facilities.": "Involucre a nuestros equipos de construcción para plataformas, infraestructura e instalaciones industriales.",
  "Engineer and install piping and utility packages aligned to your process design.": "Diseñe e instale paquetes de tuberías y servicios industriales alineados con el diseño de su proceso.",
  "Engineering": "Ingeniería",
  "Engineering excellence": "Excelencia en ingeniería",
  "Engineering for your next campaign": "Ingeniería para tu próxima campaña",
  "Engineering | MENSERCA": "Ingeniería | MENSERCA",
  "Environmental remediation and coastal recovery": "Remediación ambiental y recuperación costera",
  "Environmental remediation and coastal recovery in critical operational zones, with mitigation, compliance, and community engagement.": "Remediación ambiental y recuperación costera en zonas operativas críticas, con mitigación, cumplimiento y participación comunitaria.",
  "Environmental remediation, coastal recovery, critical-zone intervention, compliance, and community commitment.": "Remediación ambiental, recuperación costera, intervención en zonas críticas, cumplimiento y compromiso comunitario.",
  "Environmental sampling": "Muestreo ambiental",
  "Equipment balancing": "Balanceo de equipos",
  "Equipment classes": "Tipos de equipos",
  "Equipment data sheets, control philosophies": "Fichas técnicas de equipos, filosofías de control.",
  "Eudo Méndez": "Eudo Méndez",
  "Excavation": "Excavación",
  "Execution & remediation": "Ejecución y remediación",
  "Execution clients": "Clientes en ejecución",
  "Execution focus": "Enfoque de ejecución",
  "Experience": "Experiencia",
  "Explore": "Explorar",
  "Explore technical capabilities": "Explorar capacidades técnicas",
  "FEED": "FEED",
  "FEED, HAZOP": "FEED, HAZOP",
  "FEED, HAZOP, BIM": "FEED, HAZOP, BIM",
  "FEED, HAZOP, LOPA, BIM": "FEED, HAZOP, LOPA, BIM",
  "FEED, basic & detailed design": "FEED, diseño básico y detallado",
  "FEED, detailed design, or studies. Route a technical inquiry to our desk.": "FEED, diseño de detalle o estudios. Envíe una consulta técnica a nuestro escritorio.",
  "Fabrication & erection": "Fabricación y montaje",
  "Fabrication & integrity": "Fabricación e integridad",
  "Fabrication & welding": "Fabricación y soldadura",
  "Fabrication and erection of steel structures": "Fabricación y montaje de estructuras de acero.",
  "Fabrication, rotating equipment, pipelines": "Fabricación, equipos rotativos, tuberías.",
  "Fabrication, welding, commissioning": "Fabricación, soldadura, puesta en marcha.",
  "Facilities & wellpads": "Instalaciones y pozos",
  "Facility construction": "Construcción de instalaciones",
  "Fatalities": "Muertes",
  "Featured programs": "Programas destacados",
  "Field": "Campo",
  "Field Operations": "Operaciones en campo",
  "Field Operations | MENSERCA": "Operaciones en campo | MENSERCA",
  "Field execution": "Ejecución de campo",
  "Field execution in civil, mechanical, and electrical operations": "Ejecución en campo en operaciones civiles, mecánicas y eléctricas.",
  "Field execution quality": "Calidad de ejecución en campo",
  "Field inspection": "Inspección de campo",
  "Field operations": "Operaciones en campo",
  "Field supervision & QC": "Supervisión de campo y control de calidad",
  "Field supervision and quality control": "Supervisión de campo y control de calidad.",
  "Figures that reflect field hours, fleet, logistics reach, and workforce depth, structured for serious industrial clients.": "Cifras que reflejan horas de campo, flota, alcance logístico y profundidad de la fuerza laboral, estructuradas para clientes industriales serios.",
  "Flowline": "Línea de flujo",
  "Flowlines and production lines": "Líneas de flujo y líneas de producción.",
  "Footer": "Pie de página",
  "Form layout only. Wireframe fields per brief.": "Diseño de formulario únicamente. Campos de estructura alámbrica por resumen.",
  "Founded 1992": "Fundada en 1992",
  "Founded in 1992, MENSERCA is a leading contractor with 34 years of uninterrupted experience in engineering, maintenance, and construction services for the oil and industrial sectors.": "Fundada en 1992, MENSERCA es una contratista líder con 34 años de experiencia ininterrumpida en servicios de ingeniería, mantenimiento y construcción para el sector petrolero e industrial.",
  "Founded in 1992, Méndez Servicios, C.A. is an industrial contractor with 34+ years supporting oil & gas and infrastructure by integrating personnel, heavy equipment, logistics, and field execution.": "Fundada en 1992, Méndez Servicios, C.A. es un contratista industrial con más de 34 años apoyando el petróleo y el gas y la infraestructura mediante la integración de personal, equipo pesado, logística y ejecución de campo.",
  "Franclin Villadiego": "Franclin Villadiego",
  "Full projects portfolio": "Portafolio completo de proyectos",
  "Gas": "Gas",
  "Gas & water": "Gas y agua",
  "Generators": "Generadores",
  "Global sourcing": "Abastecimiento global",
  "Global sourcing & Multimode logistics": "Abastecimiento global y logística multimodal",
  "Global sourcing & multimodal logistics": "Abastecimiento global y logística multimodal",
  "Global sourcing of critical equipment and materials": "Abastecimiento global de equipos y materiales críticos",
  "Global sourcing, QA/QC, door-to-door": "Abastecimiento global, QA/QC, puerta a puerta",
  "Grading / leveling": "Nivelación",
  "Grounding & site power": "Puesta a tierra y alimentación del sitio",
  "Grounding systems": "Sistemas de puesta a tierra",
  "HAZOP": "HAZOP",
  "HAZOP / LOPA": "HAZOP/LOPA",
  "HAZOP / LOPA, simulation, BIM": "HAZOP/LOPA, simulación, BIM",
  "HSE & certified management": "HSE y gestión certificada",
  "HSE performance (sample window)": "Desempeño HSE",
  "HV": "Alto voltaje",
  "Heavy Machinery": "Maquinaria pesada",
  "Heavy machinery and logistics aligned to terrain, scope, and productivity targets.": "Maquinaria pesada y logística alineada al terreno, alcance y objetivos de productividad.",
  "Heavy machines": "Maquinaria pesada",
  "High-risk zone identification": "Identificación de zonas de alto riesgo",
  "Highest standards of safety, operational integrity, environmental responsibility, and continuous risk control across all operations.": "Los más altos estándares de seguridad, integridad operativa, responsabilidad ambiental y control continuo de riesgos en todas las operaciones.",
  "Highlights": "Aspectos destacados",
  "Home": "Hogar",
  "How we work": "Cómo trabajamos",
  "ISO": "ISO",
  "ISO 14001": "ISO 14001",
  "ISO 14001: Environment": "ISO 14001: Medio ambiente",
  "ISO 45001": "ISO 45001",
  "ISO 45001: Safety": "ISO 45001: Seguridad",
  "ISO 9001": "Norma ISO 9001",
  "ISO 9001: Quality": "ISO 9001: Calidad",
  "ISO management system narrative: Safety & Sustainability page.": "Narrativa del sistema de gestión ISO: página de seguridad y sostenibilidad.",
  "ISO narrative:": "Narrativa ISO:",
  "Including": "Incluye",
  "Industrial Maintenance": "Mantenimiento industrial",
  "Industrial Maintenance | MENSERCA": "Mantenimiento industrial | MENSERCA",
  "Industrial Utility Systems": "Sistemas de servicios industriales",
  "Industrial Utility Systems | MENSERCA": "Sistemas de servicios industriales | MENSERCA",
  "Industrial buildings & civil": "Naves industriales y civiles",
  "Industrial civil & structural": "Industrial civil y estructural",
  "Industrial civil and structural execution, from pads and earthworks through facilities, drainage, and field quality control.": "Ejecución civil y estructural industrial, desde plataformas y movimiento de tierras hasta instalaciones, drenaje y Control de calidad en campo.",
  "Industrial civil and structural works": "Obras civiles y estructurales industriales.",
  "Industrial cleaning": "Limpieza industrial",
  "Industrial contracting with regional reach and deep technical execution.": "Contratista industrial con alcance regional y profunda capacidad técnica.",
  "Industrial contractor providing engineering, procurement, construction, and maintenance services.": "Contratista industrial que brinda servicios de ingeniería, procura, construcción y mantenimiento.",
  "Industrial control and instrumentation": "Control e instrumentación industrial.",
  "Industrial cooling systems and chillers": "Sistemas de refrigeración y enfriadoras industriales.",
  "Industrial maintenance": "Mantenimiento industrial",
  "Industrial utility systems": "Sistemas de servicios industriales",
  "Infrastructure": "Infraestructura",
  "Infrastructure life extension": "Extensión de vida de la infraestructura",
  "Infrastructure life extension; preventive and corrective interventions": "Extensión de vida de la infraestructura; intervenciones preventivas y correctivas",
  "Inquiry form layout": "Diseño del formulario de consulta",
  "Inspection & environment": "Inspección y medio ambiente",
  "Inspection & environmental sampling": "Inspección y muestreo ambiental.",
  "Inspection & sampling": "Inspección y muestreo",
  "Installation and maintenance of industrial equipment": "Instalación y mantenimiento de equipos industriales.",
  "Installation, fabrication, integrity restoration, and life extension for rotating equipment, piping, tanks, and structures.": "Instalación, fabricación, restauración de integridad y extensión de vida útil de equipos estáticos y rotativos, tuberías, tanques y estructuras.",
  "Instrumentation": "Instrumentación",
  "Instrumentation & control": "Instrumentación y control",
  "Integrity": "Integridad",
  "Integrity & life extension": "Integridad y extensión de vida",
  "Integrity programs": "Programas de integridad",
  "Integrity restoration & life extension": "Restauración de integridad y extensión de vida útil",
  "Introduction": "Introducción",
  "LOPA": "LOPA",
  "LP gas and natural gas systems": "Sistemas de gas LP y gas natural",
  "Large-scale corroded line replacement, preventive maintenance, asset management, storage optimization, decarbonization.": "Reemplazo de líneas corroídas a gran escala, mantenimiento preventivo, gestión de activos, optimización del almacenamiento, descarbonización.",
  "Large-scale infrastructure support": "Soporte de infraestructura a gran escala",
  "Large-scale line replacement and sustaining work across flow stations, with asset management, storage optimization, and decarbonization focus.": "Reemplazo de líneas a gran escala y trabajos de mantenimiento en estaciones de flujo, con enfoque en la gestión de activos, la optimización del almacenamiento y la descarbonización.",
  "Large-scale replacement of corroded lines (up to ~20 km coverage)": "Reemplazo a gran escala de líneas corroídas (hasta ~20 km de cobertura)",
  "Laser alignment": "Alineación láser",
  "Laser alignment; equipment balancing": "Alineación láser; balanceo de equipos",
  "Vehicles": "Vehículos",
  "Lighting systems": "Sistemas de iluminación",
  "Local content and communities": "Contenido local y comunidades",
  "Logistics": "Logística",
  "Logistics & nationalization": "Logística y nacionalización",
  "Logistics deployment": "Despliegue logístico",
  "Logistics execution": "Ejecución logística",
  "Long-distance line replacement": "Reemplazo de línea de larga distancia",
  "Lost-time injuries": "Lesiones con pérdida de tiempo",
  "MCC": "MCC",
  "MCCs": "MCC",
  "MENSERCA": "MENSERCA",
  "MENSERCA focuses its expertise on high-level industrial and energy infrastructure.": "MENSERCA centra su experiencia en infraestructuras industriales y energéticas de alto nivel.",
  "MENSERCA is committed to the highest standards of safety, operational integrity, environmental responsibility, and continuous risk control, protecting personnel, equipment, and infrastructure under ISO 9001, ISO 14001, and ISO 45001.": "MENSERCA está comprometida con los más altos estándares de seguridad, integridad operativa, responsabilidad ambiental y control continuo de riesgos, protegiendo al personal, equipos e infraestructura bajo las normas ISO 9001, ISO 14001 e ISO 45001.",
  "MENSERCA | Industrial EPC & Field Services": "MENSERCA | EPC industrial y servicios de campo",
  "MTO/BOM, specifications, As-Built drawings": "MTO/BOM, especificaciones, planos de construcción",
  "Maintenance": "Mantenimiento",
  "Maintenance of static equipment": "Mantenimiento de equipos estáticos.",
  "Maintenance readiness": "Preparación para el mantenimiento",
  "Man-hours": "Horas-hombre",
  "Man-hours worked": "Horas-hombre trabajadas",
  "Mandatory PPE": "EPP obligatorio",
  "Maritime, air, and land logistics": "Logística marítima, aérea y terrestre",
  "Mass and energy balances": "Balances de masa y energía.",
  "Measurement, protection, and control systems": "Sistemas de medida, protección y control.",
  "Mechanical": "Mecánico",
  "Mechanical & Integrity": "Mecánica e integridad",
  "Mechanical & Integrity | MENSERCA": "Mecánica e integridad | MENSERCA",
  "Mechanical & integrity campaigns": "Campañas mecánicas y de integridad",
  "Mechanical fabrication, welding, and field pipeline installation": "Fabricación mecánica, soldadura e instalación de tuberías en campo.",
  "Medium- and high-voltage substations": "Subestaciones de media y alta tensión",
  "Medium- and high-voltage substations; power transformers; generators; MCCs": "Subestaciones de media y alta tensión; transformadores de potencia; generadores; MCC",
  "Minor maintenance and preventive services": "Servicios menores de mantenimiento y preventivos.",
  "Mobile": "Móvil",
  "Mobilize multidiscipline crews for industrial and environmental field programs.": "Movilizar equipos multidisciplinarios para programas de campo industriales y ambientales.",
  "Multidisciplinary design from concept through commissioning documentation. All work is aligned to international codes and your project stage gate.": "Diseño multidisciplinario desde el concepto hasta la documentación de puesta en marcha. Todo el trabajo está alineado con los códigos internacionales y la etapa de entrada de su proyecto.",
  "Multidisciplinary design from concept through commissioning documentation. All work is aligned with international standards.": "Diseño multidisciplinario desde el concepto hasta la documentación de puesta en marcha. Todo el trabajo se alinea con estándares internacionales.",
  "Multidisciplinary engineering, procurement, construction, and industrial maintenance under international quality and safety standards.": "Ingeniería multidisciplinaria, procura, construcción y mantenimiento industrial bajo estándares internacionales de calidad y seguridad.",
  "Multidisciplinary engineering: mechanical, piping, electrical, control, civil, structural": "Ingeniería multidisciplinar: mecánica, tuberías, eléctrica, control, civil, estructural.",
  "Multidiscipline & digital delivery": "Entrega multidisciplinaria y digital",
  "Multidiscipline execution, remediation": "Ejecución multidisciplinaria, remediación.",
  "Multidiscipline field execution": "Ejecución de campo multidisciplinar",
  "Multidiscipline field execution across civil, mechanical, and electrical scopes, with inspection, environmental sampling, and remediation.": "Ejecución de campo multidisciplinaria en ámbitos civil, mecánico y eléctrico, con inspección, muestreo ambiental y remediación.",
  "Multimodal logistics": "Logística multimodal",
  "NDT": "END / NDT",
  "National coverage": "Cobertura nacional",
  "National logistics footprint": "Huella logística nacional",
  "Navigate": "Navegar por",
  "Need a bundled EPC scope?": "¿Necesita un alcance EPC incluido?",
  "Next: Construction": "Siguiente: Construcción e infraestructura",
  "Next: Electrical": "Siguiente: Electricidad",
  "Next: Field operations": "Siguiente: Operaciones en campo",
  "Next: Maintenance": "Siguiente: Mantenimiento",
  "Next: Mechanical": "Siguiente: Mecánica",
  "Next: Procurement": "Siguiente: Procura",
  "Next: Utility systems": "Siguiente: Sistemas de servicios industriales",
  "Non-destructive testing": "Pruebas no destructivas",
  "Oil, gas & infrastructure": "Petróleo, gas e infraestructura",
  "Open": "Abierto",
  "Open menu": "Abrir menú",
  "Open the full service layout for procurement, construction, maintenance, field work, and utilities.": "Abra el diseño de servicio completo para procura, construcción, mantenimiento, trabajo en campo y servicios industriales.",
  "Operational and environmental remediation": "Remediación operativa y ambiental",
  "Operational capacity": "Capacidad operativa",
  "Operational evaluation of coastal and industrial areas": "Evaluación operativa de zonas costeras e industriales.",
  "Operational focus": "Enfoque operativo",
  "Operational focus, risk evaluation, and field measures": "Enfoque operativo, evaluación de riesgos y medidas de campo.",
  "Operational maintenance": "Mantenimiento operativo",
  "Operational maintenance and preventive services": "Mantenimiento operativo y servicios preventivos",
  "Operational risk evaluation and strict PPE / lifting protocols": "Evaluación de riesgos operativos y estrictos protocolos de izamiento y uso de EPP",
  "Operations": "Operaciones",
  "Operations Manager": "Gerente de Operaciones",
  "Other": "Otro",
  "Our commitment": "Nuestro compromiso",
  "Overhaul of pumps, compressors, and turbines": "Revisión de bombas, compresores y turbinas.",
  "P&ID": "P&ID",
  "PB": "PB",
  "PI": "PI",
  "PLC": "PLC",
  "PMBOK-based project management": "Gestión de proyectos basada en PMBOK.",
  "Pads": "Plataformas",
  "Pads & site development": "Plataformas y desarrollo de sitio",
  "Pads, earthworks, drainage": "Plataformas, movimiento de tierras, drenaje.",
  "Pads, earthworks, site development": "Plataformas, movimiento de tierra, desarrollo de sitio",
  "Performance": "Actuación",
  "Personnel protection": "Protección del personal",
  "Petro Boscán": "Petroboscán",
  "Petro Boscán, pipeline installation and trenching along a road corridor": "Petroboscán, instalación de tuberías y zanja a lo largo de un corredor vial",
  "Petro Boscán, view projects": "Petroboscán, ver proyectos",
  "Petro Independencia": "Petroindependencia",
  "Petro Independencia, paving and civil infrastructure works": "Petroindependencia, obras de pavimentación e infraestructura civil",
  "Petro Independencia, view projects": "Petroindependencia, ver proyectos",
  "PetroBoscán recognition for participation in contractor emergency response and control (RCE) activities.": "Reconocimiento de Petroboscán por participación en actividades de respuesta y control de emergencias de contratistas (RCE).",
  "PetroBoscán recognition for participation in the Learning from Incidents campaign; 268 days without disabling injuries, October 2025.": "Reconocimiento de Petroboscán por participación en la campaña \"Aprendiendo de los incidentes\"; 268 días sin lesiones incapacitantes, octubre de 2025.",
  "Petroboscan": "Petroboscán",
  "Petroboscán": "Petroboscán",
  "Petroboscán recognition for participation in contractor emergency response and control (RCE) activities.": "Reconocimiento de Petroboscán por participación en actividades de respuesta y control de emergencias de contratistas (RCE).",
  "Petroboscán recognition for participation in the Learning from Incidents campaign; 268 days without disabling injuries, October 2025.": "Reconocimiento de Petroboscán por participación en la campaña \"Aprendiendo de los incidentes\"; 268 días sin lesiones incapacitantes, octubre de 2025.",
  "Petroboscán, pipeline installation and trenching along a road corridor": "Petroboscán, instalación de tuberías y zanja a lo largo de un corredor vial",
  "Petroboscán, view projects": "Petroboscán, ver proyectos",
  "Petroindependencia": "Petroindependencia",
  "Petroindependencia, process pipeline installation and trenching": "Petroindependencia, instalación de tuberías de proceso y zanja",
  "Petroindependencia, view projects": "Petroindependencia, ver proyectos",
  "Pipeline integrity restoration": "Restauración de integridad de tuberías",
  "Pipeline integrity restoration; remaining life assessment": "Restauración de integridad de tuberías; evaluación de vida restante",
  "Pipelines": "Tuberías",
  "Piping": "Tuberías",
  "Piping & lines": "Tuberías y líneas",
  "Piping & transport": "Tuberías y transporte",
  "Piping & utilities": "Tuberías y servicios industriales",
  "Piping flexibility analysis": "Análisis de flexibilidad de tuberías.",
  "Piping flexibility; multidisciplinary mechanical/piping/civil": "Flexibilidad de tuberías; multidisciplinario mecánico/tuberías/civil",
  "Piping, steam, cooling, water, gas": "Tuberías, vapor, refrigeración, agua, gas",
  "Plan fabrication, overhaul, or integrity restoration with our technical teams.": "Planifique la fabricación, revisión o restauración de integridad con nuestros equipos técnicos.",
  "Plan shutdowns, campaigns, or operational maintenance with MENSERCA.": "Planifica paradas, campañas o mantenimientos operativos con MENSERCA.",
  "Plant shutdown planning and execution": "Planificación y ejecución de paradas de planta.",
  "Poliana Lunar": "Poliana Lunar",
  "Position / job title": "Puesto/título del trabajo",
  "Power & control": "Poder y control",
  "Power & control delivery": "Entrega de energía y control",
  "Power & distribution": "Energía y distribución",
  "Power distribution centers": "Centros de distribución de energía",
  "Power distribution centers; grounding systems": "Centros de distribución de energía; sistemas de puesta a tierra",
  "Power infrastructure": "Infraestructura eléctrica",
  "Power systems": "Sistemas de energía",
  "Power systems, substations, wellpad electrification, and industrial control, from protection and grounding through integration.": "Sistemas de energía, subestaciones, electrificación de pozos y control industrial, desde protección y puesta a tierra hasta la integración.",
  "Power systems; transmission lines (13.8 kV / 34.5 kV)": "Sistemas de energía; líneas de transmisión (13,8 kV / 34,5 kV)",
  "Power transformers": "Transformadores de potencia",
  "Precision welding": "Soldadura de precisión",
  "Precision welding; API/ASME spools": "Soldadura de precisión; carretes API/ASME",
  "Predictive": "Predictivo",
  "Predictive & asset management": "Gestión predictiva y de activos",
  "Predictive maintenance supported by digital tools and drones where appropriate": "Mantenimiento predictivo apoyado en herramientas digitales y drones cuando corresponda",
  "Predictive tools & asset care": "Herramientas predictivas y cuidado de activos",
  "Presence": "Presencia",
  "Preventive and corrective maintenance": "Mantenimiento preventivo y correctivo.",
  "Preventive and corrective technical interventions": "Intervenciones técnicas preventivas y correctivas",
  "Primary": "Principal",
  "Process & design deliverables": "Entregables de proceso y diseño",
  "Process engineering & simulation": "Ingeniería de procesos y simulación.",
  "Process piping & flowlines": "Tuberías y líneas de flujo de proceso",
  "Process piping systems": "Sistemas de tuberías de proceso",
  "Process piping, flowlines, fluids transport, and utility packages for steam, cooling, air, gas, and water.": "Tuberías de proceso, líneas de flujo, transporte de fluidos y paquetes de servicios industriales para vapor, refrigeración, aire, gas y agua.",
  "Process simulation": "Simulación de procesos",
  "Process simulation; tank design API 650/653": "Simulación de procesos; diseño de tanques API 650/653",
  "Procurement": "Procura",
  "Procurement & Logistics": "Procura y logística",
  "Procurement & Logistics | MENSERCA": "Procura y logística | MENSERCA",
  "Procurement for your next package": "Procura para su próximo proyecto",
  "Production machinery support": "Soporte de maquinaria de producción.",
  "Programs": "Programas",
  "Project 01": "Proyecto 01",
  "Project 02": "Proyecto 02",
  "Project 03": "Proyecto 03",
  "Project Management / General Manager": "Gestión de Proyectos / Gerente General",
  "Projects": "Proyectos",
  "Projects in execution": "Proyectos en ejecución",
  "Projects | MENSERCA": "Proyectos | MENSERCA",
  "Protection & facilities": "Protección e instalaciones",
  "Protocol improvement": "Mejora del protocolo",
  "QA/QC": "QA/QC",
  "QA/QC & nationalization": "QA/QC y nacionalización",
  "QA/QC, nationalization support": "QA/QC, apoyo a la nacionalización",
  "QC": "Control de calidad",
  "Qualified employees": "Empleados calificados",
  "Quality & specialized procurement": "Calidad y procura especializada",
  "Quality in the field": "Calidad en campo",
  "Refurbishment of rotating equipment": "Renovación de equipos rotativos.",
  "Regional foundations that keep mobilization and execution responsive.": "Bases regionales que mantienen una movilización y ejecución eficientes.",
  "Regulatory compliance": "Cumplimiento normativo",
  "Rehabilitation of control systems": "Rehabilitación de sistemas de control.",
  "Related projects": "Proyectos relacionados",
  "Remaining life assessment of critical assets": "Evaluación de vida restante de activos críticos",
  "Remediation": "Remediación",
  "Remediation & site services": "Servicios de remediación y sitio",
  "Remediation, decarbonization focus, and local content commitment": "Remediación, enfoque de descarbonización y compromiso con el contenido local",
  "Replacement of corroded pipelines (up to ~20 km)": "Reemplazo de tuberías corroídas (hasta ~20 km)",
  "Replacement of corroded pipelines up to 20 km": "Reemplazo de tuberías corroídas hasta 20 km.",
  "Request technical procurement and logistics support for industrial projects.": "Solicitar soporte técnico en procura y logística para proyectos industriales.",
  "Risk & compliance studies": "Estudios de riesgo y cumplimiento",
  "Risk evaluation": "Evaluación de riesgos",
  "Risk, safety & mechanical studies": "Estudios de riesgo, seguridad y mecánica.",
  "Rotating & static equipment": "Equipos estáticos y rotativos",
  "Rotating equipment & commissioning": "Equipos rotativos y puesta en marcha",
  "Rotating equipment & tanks": "Equipos rotativos y tanques",
  "SCADA / PLC": "SCADA/PLC",
  "SCADA / PLC, ESD systems": "SCADA/PLC, sistemas ESD.",
  "Safe lifting procedures": "Procedimientos seguros de izamiento",
  "Safety": "Seguridad",
  "Safety & Sustainability": "Seguridad y sostenibilidad",
  "Safety & Sustainability | MENSERCA": "Seguridad y Sostenibilidad | MENSERCA",
  "Safety & sustainability": "Seguridad y sostenibilidad",
  "Safety and sustainability": "Seguridad y sostenibilidad",
  "Safety measures": "Medidas de seguridad",
  "Scale": "Escala",
  "Scope at a glance": "Alcance de un vistazo",
  "Scope substations, wellpad power, or C&I integration for your next project.": "Consulte sobre subestaciones, energía para pozos o integración de C&I para su próximo proyecto.",
  "Sector": "Sector",
  "Select a domain": "Seleccione un dominio",
  "Service type": "Tipo de servicio",
  "Shelters / control rooms": "Refugios/salas de control",
  "Shutdown": "Paradas",
  "Shutdown planning & execution": "Planificación y ejecución de paradas",
  "Shutdowns": "Paradas",
  "Shutdowns & assets": "Paradas y activos",
  "Shutdowns & campaigns": "Paradas y campañas",
  "Shutdowns, operational maintenance, and asset programs for static and rotating equipment, controls, and predictive tools.": "Paradas, mantenimiento operativo y programas de activos para equipos estáticos y rotativos, controles y herramientas predictivas.",
  "Shutdowns, rotating and static assets, and predictive care for continuous operations.": "Paradas, activos estáticos y rotativos, y atención predictiva para operaciones continuas.",
  "Shutdowns, static & rotating assets": "Paradas, activos estáticos y rotativos",
  "Site & remediation": "Sitio y remediación",
  "Site & terrain": "Sitio y terreno",
  "Site development": "Desarrollo de sitio",
  "Site development and material handling": "Desarrollo de sitio y manejo de materiales",
  "Site services": "Servicios en sitio",
  "Skip to content": "Saltar al contenido",
  "Sourcing & logistics": "Abastecimiento y logística",
  "Sourcing & supplier coordination": "Coordinación de abastecimiento y proveedores.",
  "Sourcing footprint": "Huella de abastecimiento",
  "Sourcing in the U.S., Europe, and Asia": "Abastecimiento en EE. UU., Europa y Asia",
  "Specialized categories": "Categorías especializadas",
  "Specialized technical procurement": "contratación técnica especializada",
  "Specialized technical procurement: valves, instrumentation, specialty piping": "Categorías especializadas: contratación técnica especializada: válvulas, instrumentación y tuberías especiales.",
  "Static & rotating": "Equipos estáticos y rotativos",
  "Static & rotating assets": "Activos estáticos y rotativos",
  "Static & rotating equipment": "Equipos estáticos y rotativos",
  "Steam": "Vapor",
  "Steam & cooling": "Vapor y enfriamiento",
  "Steam generation and condensate return": "Generación de vapor y retorno de condensado.",
  "Steam, cooling, air, gas, water": "Vapor, refrigeración, aire, gas, agua.",
  "Strength": "Fortaleza",
  "Structural": "Estructural",
  "Structures & welding": "Estructuras y soldadura",
  "Submit (placeholder)": "Enviar (marcador de posición)",
  "Substation": "Subestación",
  "Substations & distribution": "Subestaciones y distribución",
  "Substations, MCC, control systems": "Subestaciones, CCM, sistemas de control.",
  "Systems": "Sistemas",
  "Systems & digital": "Sistemas digitales",
  "TBG": "TBG",
  "TBG, view projects": "TBG, ver proyectos",
  "Tank design API 650 / 653": "Diseño de tanques API 650 / 653",
  "Tank inspection, construction, and maintenance": "Inspección, construcción y mantenimiento de tanques.",
  "Technical & field workforce": "Personal técnico y de campo",
  "Technical capabilities": "Capacidades técnicas",
  "Technical depth across the full project lifecycle, from design standards through safe field execution.": "Profundidad técnica en todo el ciclo de vida del proyecto, desde los estándares de diseño hasta la ejecución segura en el campo.",
  "Technical inquiry": "Consulta técnica",
  "Technical leads for procurement support and industrial projects.": "Líderes técnicos para soporte de procura y proyectos industriales.",
  "Technical message": "Mensaje técnico",
  "Technical support, engineering, or field execution?": "¿Soporte técnico, ingeniería o ejecución en campo?",
  "Tell us which domains apply. Our team routes technical inquiries to the right discipline leads.": "Díganos qué dominios aplican. Nuestro equipo dirige las consultas técnicas a los líderes disciplinarios adecuados.",
  "Terrain preparation": "Preparación del terreno",
  "Heat generation and gas compression": "Generación de calor y compresión de gas",
  "Heat generation systems for industrial operations.": "Sistemas de generación de calor para operaciones industriales.",
  "Gas compression support and auxiliary systems.": "Soporte de compresión de gas y sistemas auxiliares.",
  "Integrated thermal and compression solutions for field execution.": "Soluciones térmicas y de compresión integradas para ejecución en campo.",
  "Three pillars of HSE execution, aligned and consistent across sites.": "Tres pilares de ejecución de HSE, alineados y consistentes en todos los sitios.",
  "Transmission lines (13.8 kV / 34.5 kV)": "Líneas de transmisión (13,8 kV / 34,5 kV)",
  "Transport systems for water, gas, and industrial fluids": "Sistemas de transporte de agua, gas y fluidos industriales.",
  "Uninterrupted industrial contracting": "Contratación industrial ininterrumpida",
  "Utilities": "Servicios industriales",
  "Utility Systems": "Sistemas de servicios industriales",
  "Surface facilities and auxiliary services": "Facilidades de superficie y servicios auxiliares",
  "VFD": "VFD",
  "VFD integration": "Integración VFD",
  "Vegetation control": "Control de vegetación",
  "Water": "Agua",
  "Water treatment and handling systems": "Sistemas de tratamiento y manejo de agua.",
  "We deliver comprehensive solutions supported by a highly skilled workforce, advanced technology, and top-tier proprietary equipment.": "Ofrecemos soluciones integrales respaldadas por una fuerza laboral altamente calificada, tecnología avanzada y equipos patentados de primer nivel.",
  "We deliver engineering, procurement, construction, maintenance, and on-site execution for energy and infrastructure projects. Safety, efficiency, and operational delivery guide every engagement.": "Brindamos ingeniería, procura, construcción, mantenimiento y ejecución en sitio para proyectos de energía e infraestructura. La seguridad, la eficiencia y la entrega operativa guían cada compromiso.",
  "We develop and execute EPC projects for the energy industry, covering engineering, procurement, construction, maintenance, and field execution.\nWe ensure asset integrity, HSE compliance, operational efficiency, and on-time delivery, aligned with international industry standards.": "Desarrollamos y ejecutamos proyectos EPC para la industria energética, abarcando ingeniería, procura, construcción, mantenimiento y ejecución en campo. Aseguramos la integridad de activos, el cumplimiento HSE, la eficiencia operativa y la entrega oportuna, conforme a estándares internacionales de la industria.",
  "We develop and execute EPC projects for the energy industry, covering engineering, procurement, construction, maintenance, and field execution. We ensure asset integrity, HSE compliance, operational efficiency, and on-time delivery, aligned with international industry standards.": "Desarrollamos y ejecutamos proyectos EPC para la industria energética, abarcando ingeniería, procura, construcción, mantenimiento y ejecución en campo. Aseguramos la integridad de activos, el cumplimiento HSE, la eficiencia operativa y la entrega oportuna, conforme a estándares internacionales de la industria.",
  "Weight & falling-risk assessment": "Evaluación de carga y riesgo de caídas",
  "Welding": "Soldadura",
  "Wellpad / Pad 5 construction": "Construcción de Macolla 5",
  "Wellpad / Pad 5, civil & electrical infrastructure, production machinery support, and well optimization services.": "Macolla 5, infraestructura civil y eléctrica, soporte de maquinaria de producción y servicios de optimización de pozos.",
  "Wellpad / pad construction": "Construcción de macollas / plataformas",
  "Wellpad and civil–electrical infrastructure with production support, wells analysis, and optimization of producing assets.": "Macolla e infraestructura civil y eléctrica con soporte a la producción, análisis de pozos y optimización de activos productores.",
  "Wellpad electrification": "Electrificación de pozos",
  "Wellpad electrification, MCC": "Electrificación de pozos, MCC",
  "Wellpad power, MCC, protection": "Alimentación de pozos, MCC, protección",
  "Wells support, analysis, maintenance, and production well optimization": "Soporte de pozos, análisis, mantenimiento y optimización de pozos de producción.",
  "What we bring": "Lo que traemos",
  "What we execute": "Lo que ejecutamos",
  "Where We Operate": "Dónde operamos",
  "Where we focus": "Dónde nos enfocamos",
  "Where we operate": "Dónde operamos",
  "Who we are": "Quiénes somos",
  "With strong operational foundations in Zulia and Anzoátegui, and a key presence in El Tigre, we are strategically positioned to serve critical energy and industrial projects across the region.": "Con sólidas bases operativas en Zulia y Anzoátegui, y una presencia clave en El Tigre, estamos estratégicamente posicionados para atender proyectos energéticos e industriales críticos en toda la región.",
  "Years of experience": "Años de experiencia",
  "Zero fatalities; zero lost-time injuries (reporting window per company records)": "Cero muertes; cero lesiones con pérdida de tiempo (período de notificación según los registros de la empresa)",
  "Zulia": "Zulia",
  "amendez@menserca.com": "amendez@menserca.com",
  "and": "y",
  "emendez@menserca.com": "emendez@menserca.com",
  "field operations": "operaciones en campo",
  "fvilladiego@menserca.com": "fvilladiego@menserca.com",
  "html": "HTML",
  "industrial utility systems": "sistemas de servicios industriales",
  "plunar@menserca.com": "plunar@menserca.com"
};
